-- Phase 1 of the admin blog management overhaul. Brings the Supabase
-- blogs table to parity with the BlogPost shape used by src/data/blogs.ts
-- so admin-published posts can carry FAQ data, ISO publish dates, and
-- the post-pivot category set.
--
-- Three additive / non-destructive changes:
--
--   1. Add `faqs jsonb not null default '[]'::jsonb`.
--      Admin posts can now store the same { q, a } pairs the static
--      articles carry. The FAQPage JSON-LD on /blog/[slug] and the
--      visible <details> accordion are gated by `post.faqs?.length > 0`,
--      so the default of an empty array is correct - a post without
--      FAQs simply doesn't render either surface.
--
--   2. Add `date_published_iso text` (nullable).
--      The Schema.org BlogPosting datePublished property expects an ISO
--      8601 Date type. The existing `date` column stores the
--      human-readable display string ("June 3, 2026") that the post
--      header uses verbatim. Keeping both means the renderer doesn't
--      have to format dates and the structured data validates cleanly.
--
--   3. Drop the category check constraint.
--      The old constraint `category in ('GUIDE','STRATEGY','INSIGHTS',
--      'NEWS')` predates the pivot and blocks the 5 categories the
--      public site now uses (AEO, Answer Engine Optimization, Local
--      SEO, SEO, Performance Ads). Rather than swap one closed enum
--      for another and force a migration every time the editorial
--      team adds a category, we drop the constraint entirely and let
--      the canonical list live in src/data/blogs.ts:blogCategories
--      (already used by the admin form's dropdown in Phase 2).
--      Adding "Strategy" or "How-to" later becomes a one-line code
--      change instead of a schema migration.

alter table public.blogs
  add column if not exists faqs jsonb not null default '[]'::jsonb;

alter table public.blogs
  add column if not exists date_published_iso text;

-- The constraint name is auto-generated by Postgres for inline check
-- constraints; it follows the pattern `<table>_<column>_check`. `if
-- exists` makes this safe to re-run.
alter table public.blogs
  drop constraint if exists blogs_category_check;

comment on column public.blogs.faqs is
  'Array of { q: string, a: string } FAQ pairs. Drives the FAQPage JSON-LD schema and the visible <details> FAQ accordion on /blog/[slug]. Empty array = no FAQ block on the post.';

comment on column public.blogs.date_published_iso is
  'ISO 8601 publish date (YYYY-MM-DD). Used by BlogPosting JSON-LD datePublished (Schema.org Date type). The human-readable `date` column stays for visible display in post headers.';
